import { AgentEvent, ArticleArtifact, ArticleCommentStatus, ArticleSummary, DialogueBriefStatus, DialogueContextKind, DialogueMessage, DialogueResponse, DomainProfileRecommendation, DomainProfileSelection, DomainProfileSummary, OutlineItem, RevisionProposal, RunResponse, WritingStandardSelection, WritingStandardSummary, WritingWorkspace } from './types';
const API_BASE = import.meta.env.VITE_API_BASE ?? 'http://localhost:8787';
export interface TaskCardRevisionResponse { article: ArticleArtifact; summary: string; changedFields: string[] }
export interface OutlineItemRevisionResponse { article: ArticleArtifact; outlineItem: OutlineItem; summary: string; changedFields: string[] }
export interface SessionResponse { id: string; userId: string; currentWorkspaceId?: string }
export interface ArticleCommentProcessResponse { article: ArticleArtifact; results: Array<{ commentId: string; blockId: string; action: 'revise' | 'explain' | 'ask'; status: ArticleCommentStatus; message: string; changed: boolean }> }
async function request<T>(path: string, options?: RequestInit): Promise<T> { const response = await fetch(`${API_BASE}${path}`, { ...options, headers: { 'Content-Type': 'application/json', ...(options?.headers ?? {}) } }); if (!response.ok) throw new Error(`${response.status} ${await response.text()}`); return response.json() as Promise<T>; }
function wsBase() { return API_BASE.replace(/^http/, 'ws'); }
export const api = {
  createSession(userId = 'demo-user') { return request<SessionResponse>('/api/sessions', { method: 'POST', body: JSON.stringify({ userId }) }); },
  listWorkspaces(userId: string) { return request<WritingWorkspace[]>(`/api/workspaces?userId=${encodeURIComponent(userId)}`); },
  createWorkspace(input: { userId?: string; name: string; memberUserIds?: string[] }) { return request<WritingWorkspace>('/api/workspaces', { method: 'POST', body: JSON.stringify(input) }); },
  deleteWorkspace(workspaceId: string, userId: string) { return request<WritingWorkspace>(`/api/workspaces/${workspaceId}`, { method: 'DELETE', body: JSON.stringify({ userId }) }); },
  listArticles(userId: string, workspaceId?: string) { const query = new URLSearchParams({ userId, view: 'summary' }); if (workspaceId) query.set('workspaceId', workspaceId); return request<ArticleSummary[]>(`/api/articles?${query.toString()}`); },
  deleteArticle(articleId: string, userId: string) { return request<ArticleSummary>(`/api/articles/${articleId}`, { method: 'DELETE', body: JSON.stringify({ userId }) }); },
  listWritingStandards() { return request<WritingStandardSummary>('/api/writing-standards'); },
  listDomainProfiles() { return request<DomainProfileSummary[]>('/api/domain-profiles'); },
  recommendDomainProfiles(rawRequirement: string) { return request<DomainProfileRecommendation[]>('/api/domain-profiles/recommend', { method: 'POST', body: JSON.stringify({ rawRequirement }) }); },
  startWritingWorkflow(input: { userId: string; sessionId?: string; workspaceId?: string; articleId?: string; message?: string; sectionId?: string; targetStage: 'task-card' | 'outline' | 'section' | 'article'; replaceExisting?: boolean; domainProfile?: DomainProfileSelection; writingStandard?: WritingStandardSelection }) { return request<RunResponse>('/api/workflows/writing/start', { method: 'POST', body: JSON.stringify(input) }); },
  resolveHumanGate(runId: string, gateId: string, input: { userId: string; decision: 'accept' | 'reject'; payload?: Record<string, unknown> }) { return request<RunResponse>(`/api/workflows/${runId}/human-gates/${gateId}/resolve`, { method: 'POST', body: JSON.stringify(input) }); },
  getRun(runId: string) { return request<RunResponse>(`/api/workflows/${runId}`); },
  getArticle(articleId: string, userId?: string) { const query = userId ? `?userId=${encodeURIComponent(userId)}` : ''; return request<ArticleArtifact>(`/api/articles/${articleId}${query}`); },
  createArticleComment(articleId: string, input: { userId?: string; blockId: string; selectedText: string; comment: string }) { return request<ArticleArtifact>(`/api/articles/${articleId}/comments`, { method: 'POST', body: JSON.stringify(input) }); },
  addArticleCommentReply(articleId: string, commentId: string, input: { userId?: string; content: string }) { return request<ArticleArtifact>(`/api/articles/${articleId}/comments/${commentId}/replies`, { method: 'POST', body: JSON.stringify(input) }); },
  deleteArticleComment(articleId: string, commentId: string, input: { userId?: string }) { return request<ArticleArtifact>(`/api/articles/${articleId}/comments/${commentId}`, { method: 'DELETE', body: JSON.stringify(input) }); },
  deleteArticleCommentReply(articleId: string, commentId: string, replyId: string, input: { userId?: string }) { return request<ArticleArtifact>(`/api/articles/${articleId}/comments/${commentId}/replies/${replyId}`, { method: 'DELETE', body: JSON.stringify(input) }); },
  processArticleComments(articleId: string, input: { userId?: string; sessionId?: string; commentIds?: string[] }) { return request<ArticleCommentProcessResponse>(`/api/articles/${articleId}/comments/process`, { method: 'POST', body: JSON.stringify(input) }); },
  listDialogueProposals(articleId: string, userId: string) { return request<RevisionProposal[]>(`/api/articles/${articleId}/dialogue/proposals?userId=${encodeURIComponent(userId)}`); },
  listDialogueMessages(articleId: string, userId: string, limit = 24) { return request<DialogueMessage[]>(`/api/articles/${articleId}/dialogue/messages?userId=${encodeURIComponent(userId)}&limit=${limit}`); },
  getDialogueBrief(articleId: string, userId: string) { return request<DialogueBriefStatus>(`/api/articles/${articleId}/dialogue/brief?userId=${encodeURIComponent(userId)}`); },
  sendDialogue(articleId: string, input: { message: string; userId?: string; sessionId?: string; pendingProposalId?: string; context: { kind: DialogueContextKind; outlineItemId?: string; blockId?: string } }) { return request<DialogueResponse>(`/api/articles/${articleId}/dialogue`, { method: 'POST', body: JSON.stringify(input) }); },
  applyDialogueProposal(articleId: string, proposalId: string, input: { userId?: string; sessionId?: string }) { return request<DialogueResponse>(`/api/articles/${articleId}/dialogue/${proposalId}/apply`, { method: 'POST', body: JSON.stringify(input) }); },
  dismissDialogueProposal(articleId: string, proposalId: string, input: { userId?: string }) { return request<RevisionProposal>(`/api/articles/${articleId}/dialogue/${proposalId}/dismiss`, { method: 'POST', body: JSON.stringify(input) }); },
  reviseTaskCard(articleId: string, input: { instruction: string; userId?: string; sessionId?: string }) { return request<TaskCardRevisionResponse>(`/api/articles/${articleId}/task-card/revise`, { method: 'POST', body: JSON.stringify(input) }); },
  confirmTaskCard(articleId: string, input: { userId?: string; sessionId?: string }) { return request<ArticleArtifact>(`/api/articles/${articleId}/task-card/confirm`, { method: 'POST', body: JSON.stringify(input) }); },
  updateOutlineItem(articleId: string, sectionId: string, input: { title: string; goal: string; userId?: string }) { return request<ArticleArtifact>(`/api/articles/${articleId}/outline/${sectionId}`, { method: 'PATCH', body: JSON.stringify(input) }); },
  reviseOutlineItem(articleId: string, sectionId: string, input: { instruction: string; userId?: string; sessionId?: string }) { return request<OutlineItemRevisionResponse>(`/api/articles/${articleId}/outline/${sectionId}/revise`, { method: 'POST', body: JSON.stringify(input) }); },
  startWriting(articleId: string, input: { userId?: string; sessionId?: string }) { return request<ArticleArtifact>(`/api/articles/${articleId}/writing/start`, { method: 'POST', body: JSON.stringify(input) }); },
  streamRunEvents(runId: string, onEvent: (event: AgentEvent) => void, onError?: (error: Event) => void) { const source = new EventSource(`${API_BASE}/api/workflows/${runId}/stream`); const eventTypes = ['workflow.started','workflow.queued','workflow.resumed','workflow.completed','workflow.failed','workflow.waiting','workflow.operation.started','workflow.operation.completed','workflow.operation.failed','review.required','node.started','node.completed','skill.started','skill.completed','artifact.updated','pi.session.created','pi.session.updated','agent.decision','tool.started','tool.completed','tool.failed','human_gate.created','human_gate.resolved','review_artifact.created','queue.enqueued','queue.dequeued','queue.completed','queue.failed','rag.http.started','rag.http.completed','rag.http.failed']; for (const type of eventTypes) source.addEventListener(type, (message) => onEvent(JSON.parse((message as MessageEvent).data) as AgentEvent)); if (onError) source.onerror = onError; return () => source.close(); },
  openEventWebSocket(runId: string, onEvent: (event: AgentEvent) => void) { const socket = new WebSocket(`${wsBase()}/api/events/ws?runId=${encodeURIComponent(runId)}`); socket.onmessage = (message) => { const payload = JSON.parse(message.data as string) as { type: string; event?: AgentEvent }; if (payload.type === 'event' && payload.event) onEvent(payload.event); }; return () => socket.close(); },
};
